
--- The UI version of the benchmarks table generated by the profiler branch of
-- the FAF repository.
Benchmarks = { }
BenchmarksReceived = false

--- The UI version of the table / class counters made throughout the sim. Is 
-- received from the sim using the Sync table.
TableCounters = { }
ClassCounters = { }

--- A list of window data containing the identifier and the window itself. The
-- expected format is: data = { Identifier = string, Window = window }
WindowData = { }

--- A list of all timer data. Represents how long the sim spents in a given
-- point in the code. Is received from the sim side using the Sync table.
Timers = { }

--- A list of all stamp data. Represents all function calls made from a given point
-- in the code. Is received from the sim side using the Sync table.
Stamps = { }